version: '3.8'
services:
  dashboard:
    container_name: dashboard
    build:
      context: dashboard
      dockerfile: Dockerfile
     volumes:
       - /grcaap_dashboard/dashboard:/app
    environment:
      VITE_API_URL: ${API_URL_HANDLER_1C}
      VITE_APP_MAP_ID: ${VITE_APP_MAP_ID}
    ports:
      - "3001:3000"
    restart: always

    networks:
      - default

networks:
   default:
     external: true
     name: nginx_docker
#frontend:
#    external: true
#    name: frontend_nginx_docker